//! zellij-logging crate root.
//!
//! Zellij plugins must be Rust binary crates rather than cdylibs: the WASI
//! runtime invokes `_start` to initialise libstd (stdin/stdout fds, panic
//! hook), and `_start` is only emitted by `bin` crates. With a cdylib the
//! wasm loads but every host-to-plugin call fails with `could not find
//! exported function`.
//!
//! Layout:
//! - `ansi`, `config`, `template`, `tracker` are pure-data modules that
//!   compile on every target and are covered by unit tests via `cargo test`.
//! - `plugin` holds the `State` struct and `ZellijPlugin` impl, gated to
//!   wasm because it pulls in `zellij-tile` which only links under WASI.
//! - The `register_plugin!` invocation lives here, at the crate root, so
//!   the `fn main()` it generates becomes the binary's entry point.

mod ansi;
mod config;
mod template;
mod tracker;

#[cfg(target_family = "wasm")]
mod plugin;

// `register_plugin!` expands to trait-method calls (`load`, `update`,
// `pipe`, `render`) on the plugin state, so the `ZellijPlugin` trait has
// to be in scope at the call site. Pull the whole prelude in for
// convenience and to match what the macro's documentation assumes.
#[cfg(target_family = "wasm")]
use zellij_tile::prelude::*;

#[cfg(target_family = "wasm")]
register_plugin!(crate::plugin::State);

// Stub entry for non-wasm builds. `cargo test` and `cargo check` on the
// host hit this; the wasm build instead uses the `fn main` generated by
// `register_plugin!` above.
#[cfg(not(target_family = "wasm"))]
fn main() {
    eprintln!(
        "zellij-logging is a Zellij WASM plugin. Build it with: \n  \
        cargo build --release --target wasm32-wasip1"
    );
    std::process::exit(1);
}
